### ISSUE TITLE
PlaceholderAPI not working

### ISSUE THREAD

**Issue by DrkMatr1984** [EDGRRRRs/DivinityEconomy#58]
**Describe the bug**
PlaceholderAPI is clearly installed and working yet divinity economy does not recognize it on load.

**To Reproduce**
[Hastebin](https://www.toptal.com/developers/hastebin/fuyojusiye.yaml)

Relevant log parts are astericked

**Expected behavior**
Should recognize PlaceholderAPI and register its expansions

**Context**
Server Version: 1.18.1
Server Type(Spigot/Paper): paper
Additional Information:

**Comment by EDGRRRRs** [comment]
https://github.com/EDGRRRRs/DivinityEconomy/releases/tag/1.18.4-RC3
